MAINT: fix small typo in `small_dynamic_array.h`
on clang-19, this causes:
```
../scipy/_lib/_uarray/small_dynamic_array.h(145,18): error: reference to non-static member function must be called
  145 |     size_ = copy.size;
      |             ~~~~~^~~~
1 error generated.
```

Co-authored-by: h-vetinari <h.vetinari@gmx.com>